[package]
name = "RogueLike2023"
version = "0.1.0"
authors = ["William Cordova"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = { version = "0.8.7" }